#!/bin/bash
### ---
### name: 'MERGE_FILTERED (filtered:merged.rev2.gff3)'
### container: 'quay.io/biocontainers/biopython:1.84'
### outputs:
### - 'merged.rev2.gff3'
### - 'merged.rev2.audit.tsv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="\$PATH:/home/primeline/Data/IRnotator/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/primeline/Data/IRnotator/work/d9/025420cdfbc9d304587409c085c569/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 --memory 8192m -e "NXF_TASK_WORKDIR" -v /home/primeline/Data/IRnotator:/home/primeline/Data/IRnotator -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID quay.io/biocontainers/biopython:1.84 /bin/bash -c "eval $(nxf_container_env); /bin/bash -ue /home/primeline/Data/IRnotator/work/d9/025420cdfbc9d304587409c085c569/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f Dmagna_LRV_rnd1.gff
    rm -f sequence_registry.tsv
    rm -f Dmagna_LRV_snap-aug.gff
    rm -f merge_ir_isoforms.py
    rm -f Dmagna_LRV_IRs_braker_fixed.gff
    rm -f GCA_030254905.1_UOB_LRV0_1_genomic.gff
    rm -f decision.tsv
    ln -s /home/primeline/Data/IRnotator/test/multi_gff/annotations/Dmagna_LRV_rnd1.gff Dmagna_LRV_rnd1.gff
    ln -s /home/primeline/Data/IRnotator/work/8a/4b3bf6a395cabcc76f84030982b538/sequence_registry.tsv sequence_registry.tsv
    ln -s /home/primeline/Data/IRnotator/test/multi_gff/annotations/Dmagna_LRV_snap-aug.gff Dmagna_LRV_snap-aug.gff
    ln -s /home/primeline/Data/IRnotator/bin/merge_ir_isoforms.py merge_ir_isoforms.py
    ln -s /home/primeline/Data/IRnotator/test/multi_gff/annotations/Dmagna_LRV_IRs_braker_fixed.gff Dmagna_LRV_IRs_braker_fixed.gff
    ln -s /home/primeline/Data/IRnotator/test/multi_gff/annotations/GCA_030254905.1_UOB_LRV0_1_genomic.gff GCA_030254905.1_UOB_LRV0_1_genomic.gff
    ln -s /home/primeline/Data/IRnotator/work/a4/90d4099f3ad69d0bf37e9f93bb0747/decision.tsv decision.tsv
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/primeline/Data/IRnotator/work/d9/025420cdfbc9d304587409c085c569/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
