#!/bin/bash
### ---
### name: 'PREPARE_MANUAL_REVIEW (prepare_manual_review)'
### container: 'null'
### outputs:
### - 'manual_review'
### - 'manual_review/review-manifest.json'
### - 'manual_review/topology-reviewer.html'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/primeline/Data/IRnotator/work/dd/2da29d2c5254d950c147d55baeb5f0/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/primeline/Data/IRnotator/work/dd/2da29d2c5254d950c147d55baeb5f0/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f IRN_000545
    rm -f IRN_007719
    rm -f IRN_003979
    rm -f IRN_004513
    rm -f IRN_002115
    rm -f IRN_003126
    rm -f IRN_008638
    rm -f IRN_007724
    rm -f IRN_004179
    rm -f IRN_001580
    rm -f IRN_005087
    rm -f IRN_004033
    rm -f IRN_005088
    rm -f IRN_006177
    rm -f IRN_008772
    rm -f IRN_008771
    rm -f IRN_009061
    rm -f IRN_005086
    rm -f IRN_007164
    rm -f IRN_008770
    rm -f IRN_004080
    rm -f IRN_009014
    rm -f IRN_001887
    rm -f IRN_008919
    rm -f IRN_001305
    rm -f IRN_002268
    rm -f IRN_002126
    rm -f IRN_005219
    rm -f IRN_007517
    rm -f IRN_001677
    rm -f IRN_001296
    rm -f IRN_001670
    rm -f IRN_006600
    rm -f IRN_007657
    rm -f IRN_007656
    rm -f IRN_006587
    rm -f IRN_007710
    rm -f IRN_008403
    rm -f IRN_005576
    rm -f IRN_006588
    rm -f sequence_registry.tsv
    rm -f IRN_004020
    rm -f IRN_007872
    rm -f hardcoded_scores.tsv
    rm -f IRN_004342
    rm -f IRN_009191
    rm -f IRN_002340
    rm -f topology-reviewer.html
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_000545 IRN_000545
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007719 IRN_007719
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_003979 IRN_003979
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004513 IRN_004513
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_002115 IRN_002115
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_003126 IRN_003126
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008638 IRN_008638
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007724 IRN_007724
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004179 IRN_004179
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001580 IRN_001580
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_005087 IRN_005087
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004033 IRN_004033
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_005088 IRN_005088
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_006177 IRN_006177
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008772 IRN_008772
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008771 IRN_008771
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_009061 IRN_009061
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_005086 IRN_005086
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007164 IRN_007164
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008770 IRN_008770
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004080 IRN_004080
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_009014 IRN_009014
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001887 IRN_001887
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008919 IRN_008919
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001305 IRN_001305
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_002268 IRN_002268
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_002126 IRN_002126
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_005219 IRN_005219
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007517 IRN_007517
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001677 IRN_001677
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001296 IRN_001296
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_001670 IRN_001670
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_006600 IRN_006600
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007657 IRN_007657
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007656 IRN_007656
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_006587 IRN_006587
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007710 IRN_007710
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_008403 IRN_008403
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_005576 IRN_005576
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_006588 IRN_006588
    ln -s /home/primeline/Data/IRnotator/work/b4/84b77a4a29b0f34b76eb52b9fe3be1/sequence_registry.tsv sequence_registry.tsv
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004020 IRN_004020
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_007872 IRN_007872
    ln -s /home/primeline/Data/IRnotator/work/9f/35bdf735e3c32b43e8e18b076df7fc/hardcoded_scores.tsv hardcoded_scores.tsv
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_004342 IRN_004342
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_009191 IRN_009191
    ln -s /home/primeline/Data/IRnotator/work/e9/be2bd86ec74c898c351e68749a314c/deeptmhmm_results/IRN_002340 IRN_002340
    ln -s /home/primeline/Data/IRnotator/assets/reviewer/topology-reviewer.html topology-reviewer.html
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/primeline/Data/IRnotator/work/dd/2da29d2c5254d950c147d55baeb5f0/.command.begin
    set +u
    set -u
    export PATH="$PATH:/home/primeline/Data/IRnotator/bin"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
