#!/bin/bash
### ---
### name: 'PREPARE_MANUAL_REVIEW (prepare_manual_review:1:2)'
### container: 'quay.io/biocontainers/biopython:1.84'
### outputs:
### - 'manual_review'
### - 'manual_review/review-manifest.json'
### - 'manual_review/topology-reviewer.html'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="\$PATH:/home/primeline/Data/IRnotator/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/primeline/Data/IRnotator/work/58/b41854c1e7bbd640a29c3da7accd3c/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 --memory 4096m -e "NXF_TASK_WORKDIR" -v /home/primeline/Data/IRnotator:/home/primeline/Data/IRnotator -w "$NXF_TASK_WORKDIR" --name $NXF_BOXID quay.io/biocontainers/biopython:1.84 /bin/bash -c "eval $(nxf_container_env); /bin/bash -ue /home/primeline/Data/IRnotator/work/58/b41854c1e7bbd640a29c3da7accd3c/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013102 IRN_013102
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_009880 IRN_009880
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013101 IRN_013101
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_009883 IRN_009883
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_014672 IRN_014672
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038405 IRN_038405
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038406 IRN_038406
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013103 IRN_013103
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031695 IRN_031695
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031693 IRN_031693
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031694 IRN_031694
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031692 IRN_031692
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_023706 IRN_023706
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_041817 IRN_041817
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002214 IRN_002214
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002215 IRN_002215
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033506 IRN_033506
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002216 IRN_002216
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033505 IRN_033505
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_029258 IRN_029258
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046832 IRN_046832
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046833 IRN_046833
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031684 IRN_031684
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031685 IRN_031685
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002217 IRN_002217
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006822 IRN_006822
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006823 IRN_006823
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045071 IRN_045071
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006147 IRN_006147
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006145 IRN_006145
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006146 IRN_006146
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013109 IRN_013109
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013108 IRN_013108
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_035277 IRN_035277
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_010772 IRN_010772
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_035832 IRN_035832
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018012 IRN_018012
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006709 IRN_006709
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005739 IRN_005739
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006708 IRN_006708
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005737 IRN_005737
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005738 IRN_005738
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006834 IRN_006834
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005740 IRN_005740
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_003685 IRN_003685
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_010403 IRN_010403
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045047 IRN_045047
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045048 IRN_045048
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_010408 IRN_010408
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018703 IRN_018703
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018702 IRN_018702
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018705 IRN_018705
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_040954 IRN_040954
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018704 IRN_018704
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_016521 IRN_016521
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_016522 IRN_016522
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_017733 IRN_017733
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018701 IRN_018701
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018700 IRN_018700
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038096 IRN_038096
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_007815 IRN_007815
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_030489 IRN_030489
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005750 IRN_005750
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038407 IRN_038407
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012210 IRN_012210
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018677 IRN_018677
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018676 IRN_018676
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018679 IRN_018679
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018678 IRN_018678
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046228 IRN_046228
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018675 IRN_018675
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046230 IRN_046230
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_000471 IRN_000471
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006695 IRN_006695
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006696 IRN_006696
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006572 IRN_006572
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006693 IRN_006693
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006694 IRN_006694
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006691 IRN_006691
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006571 IRN_006571
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006692 IRN_006692
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046231 IRN_046231
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018688 IRN_018688
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018687 IRN_018687
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018689 IRN_018689
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018684 IRN_018684
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018683 IRN_018683
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019896 IRN_019896
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018686 IRN_018686
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018685 IRN_018685
    ln -s /home/primeline/Data/IRnotator/work/09/3fefbfc42ba1527c0d382a78a46e9c/review.tsv review.tsv
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018680 IRN_018680
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012580 IRN_012580
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005803 IRN_005803
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018682 IRN_018682
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018681 IRN_018681
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019890 IRN_019890
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_001333 IRN_001333
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006902 IRN_006902
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_001332 IRN_001332
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031632 IRN_031632
    ln -s /home/primeline/Data/IRnotator/work/a6/0e912b45881258d8c43382dbe79022/hardcoded_scores.tsv hardcoded_scores.tsv
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012579 IRN_012579
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045154 IRN_045154
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_010297 IRN_010297
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_011021 IRN_011021
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018699 IRN_018699
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018698 IRN_018698
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018695 IRN_018695
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038183 IRN_038183
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018694 IRN_018694
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018697 IRN_018697
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018696 IRN_018696
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018690 IRN_018690
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006903 IRN_006903
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018693 IRN_018693
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006904 IRN_006904
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018692 IRN_018692
    ln -s /home/primeline/Data/IRnotator/work/60/56f69b5e7e73a5570851ac2edd1df8/deeptmhmm_features.tsv deeptmhmm_features.tsv
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031667 IRN_031667
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038181 IRN_038181
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_023258 IRN_023258
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046699 IRN_046699
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046456 IRN_046456
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046698 IRN_046698
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046455 IRN_046455
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_014782 IRN_014782
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_009752 IRN_009752
    ln -s /home/primeline/Data/IRnotator/bin/render_gene_cds.py render_gene_cds.py
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_007570 IRN_007570
    ln -s /home/primeline/Data/IRnotator/work/a4/90d4099f3ad69d0bf37e9f93bb0747/decision.tsv decision.tsv
    ln -s /home/primeline/Data/IRnotator/assets/reviewer/topology-reviewer.html topology-reviewer.html
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033590 IRN_033590
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_016454 IRN_016454
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013061 IRN_013061
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_016450 IRN_016450
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018750 IRN_018750
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038360 IRN_038360
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051580 IRN_051580
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018752 IRN_018752
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018751 IRN_018751
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013062 IRN_013062
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031967 IRN_031967
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051577 IRN_051577
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051576 IRN_051576
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051575 IRN_051575
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051574 IRN_051574
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051579 IRN_051579
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033589 IRN_033589
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051578 IRN_051578
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046436 IRN_046436
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045105 IRN_045105
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046435 IRN_046435
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045100 IRN_045100
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_048055 IRN_048055
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019737 IRN_019737
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_015377 IRN_015377
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_038359 IRN_038359
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045106 IRN_045106
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046438 IRN_046438
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045107 IRN_045107
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_016461 IRN_016461
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033588 IRN_033588
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_020148 IRN_020148
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_020149 IRN_020149
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046681 IRN_046681
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002185 IRN_002185
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_049395 IRN_049395
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033492 IRN_033492
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012435 IRN_012435
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012556 IRN_012556
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013082 IRN_013082
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013081 IRN_013081
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_015386 IRN_015386
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051562 IRN_051562
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051561 IRN_051561
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051560 IRN_051560
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_033493 IRN_033493
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_003721 IRN_003721
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_026720 IRN_026720
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_030779 IRN_030779
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051555 IRN_051555
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_003720 IRN_003720
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051554 IRN_051554
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_042050 IRN_042050
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051553 IRN_051553
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051552 IRN_051552
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051559 IRN_051559
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051558 IRN_051558
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_026722 IRN_026722
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051557 IRN_051557
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051556 IRN_051556
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002073 IRN_002073
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002075 IRN_002075
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002072 IRN_002072
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_044479 IRN_044479
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013094 IRN_013094
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_000215 IRN_000215
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051573 IRN_051573
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_000216 IRN_000216
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051572 IRN_051572
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_000217 IRN_000217
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013096 IRN_013096
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051571 IRN_051571
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_000218 IRN_000218
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013095 IRN_013095
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_035780 IRN_035780
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051570 IRN_051570
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051566 IRN_051566
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051565 IRN_051565
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006569 IRN_006569
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051564 IRN_051564
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051563 IRN_051563
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006568 IRN_006568
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051569 IRN_051569
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051568 IRN_051568
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006687 IRN_006687
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051567 IRN_051567
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_008983 IRN_008983
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_046303 IRN_046303
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_042068 IRN_042068
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031619 IRN_031619
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018714 IRN_018714
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018713 IRN_018713
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018716 IRN_018716
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013264 IRN_013264
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018715 IRN_018715
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018710 IRN_018710
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018712 IRN_018712
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019006 IRN_019006
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018711 IRN_018711
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019005 IRN_019005
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018037 IRN_018037
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018036 IRN_018036
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051540 IRN_051540
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005768 IRN_005768
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051533 IRN_051533
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005769 IRN_005769
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_026466 IRN_026466
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051532 IRN_051532
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_026222 IRN_026222
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051531 IRN_051531
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051530 IRN_051530
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051537 IRN_051537
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051536 IRN_051536
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_003466 IRN_003466
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051535 IRN_051535
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_003465 IRN_003465
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051539 IRN_051539
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051538 IRN_051538
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018707 IRN_018707
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018706 IRN_018706
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018709 IRN_018709
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018708 IRN_018708
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018725 IRN_018725
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018724 IRN_018724
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018727 IRN_018727
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018726 IRN_018726
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018721 IRN_018721
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018720 IRN_018720
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018723 IRN_018723
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018722 IRN_018722
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002019 IRN_002019
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_019011 IRN_019011
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051551 IRN_051551
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051550 IRN_051550
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005416 IRN_005416
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051544 IRN_051544
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005417 IRN_005417
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_020591 IRN_020591
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051543 IRN_051543
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051542 IRN_051542
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051541 IRN_051541
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005775 IRN_005775
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051548 IRN_051548
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051547 IRN_051547
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005773 IRN_005773
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006620 IRN_006620
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051546 IRN_051546
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_005774 IRN_005774
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006621 IRN_006621
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051545 IRN_051545
    ln -s /home/primeline/Data/IRnotator/work/8a/4b3bf6a395cabcc76f84030982b538/sequence_registry.tsv sequence_registry.tsv
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006068 IRN_006068
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006860 IRN_006860
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_002020 IRN_002020
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_035835 IRN_035835
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006067 IRN_006067
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051549 IRN_051549
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018718 IRN_018718
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_030706 IRN_030706
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018717 IRN_018717
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_030707 IRN_030707
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_010559 IRN_010559
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018719 IRN_018719
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018736 IRN_018736
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018735 IRN_018735
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018738 IRN_018738
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018737 IRN_018737
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018732 IRN_018732
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018731 IRN_018731
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018734 IRN_018734
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018733 IRN_018733
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031157 IRN_031157
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018730 IRN_018730
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051515 IRN_051515
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_031700 IRN_031700
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051514 IRN_051514
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051513 IRN_051513
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_006871 IRN_006871
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051519 IRN_051519
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051518 IRN_051518
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051517 IRN_051517
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051516 IRN_051516
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018729 IRN_018729
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018728 IRN_018728
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018747 IRN_018747
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_015238 IRN_015238
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018746 IRN_018746
    ln -s /home/primeline/Data/IRnotator/mulit_GFF_test2/merged_gff/merged.rev1.gff3 merged.rev1.gff3
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018748 IRN_018748
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018743 IRN_018743
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_047705 IRN_047705
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_012764 IRN_012764
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018742 IRN_018742
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018745 IRN_018745
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018744 IRN_018744
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018068 IRN_018068
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018741 IRN_018741
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018740 IRN_018740
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013052 IRN_013052
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018066 IRN_018066
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_013051 IRN_013051
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_049333 IRN_049333
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051522 IRN_051522
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_028897 IRN_028897
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051521 IRN_051521
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051526 IRN_051526
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_048920 IRN_048920
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051525 IRN_051525
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051524 IRN_051524
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_028899 IRN_028899
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051523 IRN_051523
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045533 IRN_045533
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045534 IRN_045534
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051529 IRN_051529
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051528 IRN_051528
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_051527 IRN_051527
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045650 IRN_045650
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_018739 IRN_018739
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_036948 IRN_036948
    ln -s /home/primeline/Data/IRnotator/work/0f/4be809a04dbf8ee61bf51d0c81aae0/deeptmhmm_results/IRN_045651 IRN_045651
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/primeline/Data/IRnotator/work/58/b41854c1e7bbd640a29c3da7accd3c/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
