#!/bin/bash
### ---
### name: 'PREPARE_MANUAL_REVIEW (prepare_manual_review:1:2)'
### container: 'quay.io/biocontainers/biopython:1.84'
### outputs:
### - 'manual_review'
### - 'manual_review/review-manifest.json'
### - 'manual_review/topology-reviewer.html'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="\$PATH:/home/primeline/Data/IRnotator/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/primeline/Data/IRnotator/work/71/d0473d51fc9cdb56c76a69ba89b3f1/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 --memory 4096m -e "NXF_TASK_WORKDIR" -v /home/primeline/Data/IRnotator:/home/primeline/Data/IRnotator -w "$NXF_TASK_WORKDIR" -u $(id -u):$(id -g) --name $NXF_BOXID quay.io/biocontainers/biopython:1.84 /bin/bash -c "eval $(nxf_container_env); /bin/bash -ue /home/primeline/Data/IRnotator/work/71/d0473d51fc9cdb56c76a69ba89b3f1/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f merged.rev1.gff3
    rm -f review.tsv
    rm -f IRN_000006
    rm -f IRN_000007
    rm -f IRN_000008
    rm -f IRN_000009
    rm -f IRN_000002
    rm -f IRN_000013
    rm -f IRN_000003
    rm -f IRN_000004
    rm -f IRN_000005
    rm -f deeptmhmm_features.tsv
    rm -f render_gene_cds.py
    rm -f IRN_000010
    rm -f IRN_000011
    rm -f IRN_000001
    rm -f IRN_000012
    rm -f sequence_registry.tsv
    rm -f hardcoded_scores.tsv
    rm -f decision.tsv
    rm -f topology-reviewer.html
    ln -s /home/primeline/Data/IRnotator/test_warning/merged_gff/merged.rev1.gff3 merged.rev1.gff3
    ln -s /home/primeline/Data/IRnotator/work/9c/ddafc93f0b9806f0c2d5d30ba1d605/review.tsv review.tsv
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000006 IRN_000006
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000007 IRN_000007
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000008 IRN_000008
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000009 IRN_000009
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000002 IRN_000002
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000013 IRN_000013
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000003 IRN_000003
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000004 IRN_000004
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000005 IRN_000005
    ln -s /home/primeline/Data/IRnotator/work/a7/4832fe5a1b0550318e7cb68563d13d/deeptmhmm_features.tsv deeptmhmm_features.tsv
    ln -s /home/primeline/Data/IRnotator/bin/render_gene_cds.py render_gene_cds.py
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000010 IRN_000010
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000011 IRN_000011
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000001 IRN_000001
    ln -s /home/primeline/Data/IRnotator/work/dc/458c4ad47f7f2a71724e64de05c311/deeptmhmm_results.complete/IRN_000012 IRN_000012
    ln -s /home/primeline/Data/IRnotator/work/3c/e0a3addd28a98d982fe3ff37a59e87/sequence_registry.tsv sequence_registry.tsv
    ln -s /home/primeline/Data/IRnotator/work/5f/6aaa06dca12bea557aa6c5efec6f9a/hardcoded_scores.tsv hardcoded_scores.tsv
    ln -s /home/primeline/Data/IRnotator/work/e9/f688125c8485e5feaa8488d280329c/decision.tsv decision.tsv
    ln -s /home/primeline/Data/IRnotator/assets/reviewer/topology-reviewer.html topology-reviewer.html
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/primeline/Data/IRnotator/work/71/d0473d51fc9cdb56c76a69ba89b3f1/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
